# Numpy Tutorials

In [1]:
import numpy as np

In [2]:
myarr = np.array([[1,2,3,45,35]] , np.int64)

In [3]:
myarr[0,1]

np.int64(2)

In [4]:
myarr.shape

(1, 5)

In [5]:
myarr.dtype

dtype('int64')

In [6]:
myarr[0,1] = 66

In [7]:
myarr


array([[ 1, 66,  3, 45, 35]])

# Array creation in numpy

In [12]:
listarray = np.array([[3,2,1] , [6,5,4] , [9,8,7]])

In [13]:
listarray

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [14]:
listarray.dtype

dtype('int64')

In [15]:
listarray.shape

(3, 3)

In [16]:
listarray.size

9

In [17]:
np.array({34,35,36})

array({34, 35, 36}, dtype=object)

In [18]:
zero = np.zeros((2,2))

In [19]:
zero

array([[0., 0.],
       [0., 0.]])

In [20]:
rng  = np.arange(10)

In [21]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
lspace = np.linspace(1,5,4)

In [27]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [30]:
emp = np.empty((4,6))

In [31]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        6.23054293e-307, 8.90105597e-307, 6.23053614e-307],
       [7.56592338e-307, 2.22522597e-306, 1.33511969e-306,
        1.78022342e-306, 8.45602762e-307, 8.06632139e-308],
       [1.11257852e-307, 6.23038336e-307, 6.23053954e-307,
        9.34609790e-307, 8.45593934e-307, 9.34600963e-307],
       [1.78021527e-306, 6.89809225e-307, 7.56603881e-307,
        1.11260144e-306, 6.89812281e-307, 2.22522596e-306]])

In [32]:
emp_like = np.empty_like(lspace)

In [33]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [34]:
ide = np.identity(45)

In [35]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [36]:
ide.shape

(45, 45)

In [37]:
arr = np.arange(99)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [41]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [42]:
arr = arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [43]:
arr.shape

(99,)

In [44]:
x = [[1,2,3] , [4,5,6 ],[7,8,0]]

In [45]:
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [46]:
ar.sum(axis=0)

array([12, 15,  9])

In [47]:
ar.sum(axis=1)

array([ 6, 15, 15])

In [49]:
 ar.T


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 0]])

In [50]:
ar.flat

In [51]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
0


In [52]:
ar.ndim

2

In [53]:
ar.size

9

In [54]:
ar.nbytes

72

In [55]:
one = np.array([1,2,3])

In [56]:
one.argmax()

np.int64(2)

In [59]:
one.argsort()

array([0, 1, 2])

In [62]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [63]:
ar.argmin()


np.int64(8)

In [64]:
ar.argmax()

np.int64(7)

In [65]:
ar.argmax(axis=0)

array([2, 2, 1])

In [66]:
ar.argmax(axis=1)

array([2, 2, 1])

In [67]:
ar.argsort(axis=0)

array([[0, 0, 2],
       [1, 1, 0],
       [2, 2, 1]])

In [68]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [69]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 0])

In [70]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [72]:
ar2 = np.array([[0,9,8],[7,6,5],[4,3,2]])

In [73]:
ar + ar2

array([[ 1, 11, 11],
       [11, 11, 11],
       [11, 11,  2]])

In [74]:
ar * ar2

array([[ 0, 18, 24],
       [28, 30, 30],
       [28, 24,  0]])

In [75]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [76]:
ar2

array([[0, 9, 8],
       [7, 6, 5],
       [4, 3, 2]])

In [77]:
ar * ar2

array([[ 0, 18, 24],
       [28, 30, 30],
       [28, 24,  0]])

In [78]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 0.        ]])

In [79]:
ar.sum()

np.int64(36)

In [80]:
ar.min()
ar.max()

np.int64(8)

In [81]:
ar.max()

np.int64(8)

In [82]:
ar.min()

np.int64(0)

In [83]:
ar.min


<function ndarray.min(axis=None, out=None, **kwargs)>

In [84]:
ar.min(axis=0)

array([1, 2, 0])

In [85]:
np.where(ar > 5)

(array([1, 2, 2]), array([2, 0, 1]))

In [86]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [87]:
np.count_nonzero(ar)

np.int64(8)

In [88]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [89]:
import sys


In [91]:
py_ar = [0,4,55,2]

In [92]:
np_ar = np.array(py_ar)

In [93]:
sys.getsizeof(1) * len(py_ar)

112

In [94]:
np_ar.itemsize * np_ar.size

32

In [95]:
np_ar.tolist()

[0, 4, 55, 2]

In [96]:
num = np.array([1,2,3])

In [97]:
num

array([1, 2, 3])

In [98]:
print(num + 10)

[11 12 13]


In [99]:
students = np.array(["Ali", "Sara", "Bilal", "Hina"])
scores = np.array([72, 95, 60, 88])

In [100]:
order = np.argsort(students)

In [101]:
order

array([0, 2, 3, 1])

In [102]:
print("elements in sorted order" , stdents[order])

NameError: name 'stdents' is not defined

In [103]:
students[order]

array(['Ali', 'Bilal', 'Hina', 'Sara'], dtype='<U5')

In [104]:
desc = order[::-1]

In [105]:
students[desc]

array(['Sara', 'Hina', 'Bilal', 'Ali'], dtype='<U5')